name: Update README with QOTD
on:
  workflow_dispatch: # triggers manually
  schedule:
  - cron: "0 0 * * *" # triggers every midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
    - name: Install node dependencies
      run: npm install
    - name: Run QOTD action
      uses: ./ # Uses an action in the root directory
      with:
         category: 'life'
    - name: Commit and push update
      run: |-
        git config --global user.email "will19910101@163.com"
        git config --global user.name "wei100"
        git add -A
        git commit -m "Added QOTD from GitHub Actions"
        git push
